sudo: required
services:
    - docker

before_install:
    - docker build -t robinio/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true robinio/react-test npm test

after_success:
    - docker build -t robinio/multi-client ./client
    - docker build -t robinio/multi-nginx ./nginx
    - docker build -t robinio/multi-server ./server
    - docker build -t robinio/multi-worker ./worker
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Push to docker hub
    - docker push robinio/multi-client
    - docker push robinio/multi-nginx
    - docker push robinio/multi-server
    - docker push robinio/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-774035722741
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY


    